image: Visual Studio 2015

version: 1.0.{build}
skip_tags: true
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

environment:
  CODECOV_TOKEN:
    secure: 04463347-ad4f-4ff4-8d48-958fd4acdd77

build:
  project: PayFlex.Client.sln
  verbosity: minimal

test_script:
- OpenCover.Console.exe -register:user  -target:nunit-console.exe -targetargs:"/testcontainer:"".\PayFlex.Client.Test\bin\Debug\PayFlex.Client.Test.dll" -filter:"+[PayFlexClientTest*]*" -output:".\PayFlex.Client.Test_coverage.xml"
                                                                    
- codecov -f "PayFlex.Client.Test_coverage.xml